name: Build

on:
  pull_request:
  push:
    branches: "**"

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "15.x"
      - name: Install dependencies
        run: npm ci
      - name: Install Obsidian
        run: |
          wget -q https://github.com/obsidianmd/obsidian-releases/releases/download/v0.15.9/Obsidian-0.15.9-universal.dmg
          sudo hdiutil attach Obsidian-0.15.9-universal.dmg
          sudo cp -rf "/Volumes/Obsidian 0.15.9-universal/Obsidian.app" /Applications
          sudo hdiutil detach "/Volumes/Obsidian 0.15.9-universal"
      - name: Lint
        run: npm run lint
      - name: Test
        run: |
          npm run build-with-tests
          npm test
